[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "steak-project-api"
version = "0.0.1"
dependencies = []

[tool.setuptools]
packages = ["steak_project_api"]
