name: Tests

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Default
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Install project
      run: pip install .

    - name: Run tests with PyTest
      run: python -m pytest
